name: Build & Deploy to Railway

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TestApi.sln

      - name: Build
        run: dotnet build TestApi.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test TestApi.sln --no-build --configuration Release

  dockerize-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/railway-github-actions@v0
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment: ${{ secrets.RAILWAY_ENVIRONMENT }}
          serviceName: ${{ secrets.RAILWAY_SERVICE_NAME }}
